version: "3"
services: 
    server:
        build: .
        ports: 
            - "3000:3000"
        depends_on: [mongo]
        links: 
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports: 
            - "3001:27017"


    